### ISSUE TITLE
Missing assets in code/prebuilt version

### ISSUE THREAD

**Issue by csgamedev4linux** [demonixis/C3DE#2]
I've downloaded your master.zip and tried to compile the editor myself but when it runs, Visual Studio says "Missing file 'BasicEffect.fx'" or something like that and I cannot run the editor. Is there a way to solve the problem?

Thanks in advance!

**Comment by demonixis** [comment]
Hi,

Thank you for trying it. You have to compile the sample first, then to copy Content folder into the content folder of the Editor. I know it's bad but the editor is still in early stage for now.

I'll try to fix that tomorrow!

**Comment by csgamedev4linux** [comment]
Thank you!

P.S. the concret message is the following:
An Exception of the type "Microsoft.Xna.Framework.Content.ContentLoadException" is appeared in MonoGame.Framework.dll.
Additional Information: Could not load FX/SimpleEffect asset as a non-content file!

**Comment by csgamedev4linux** [comment]
Well, tried that but didn't work...
Same error in the file "SimpleMaterial.cs" in the main DLL (C3DE.dll)...

**Comment by csgamedev4linux** [comment]
Sorry, but I think it could be solved by uploading your precompiled version...

**Comment by demonixis** [comment]
Hi,
I'll fix that asap, I can't do that right now sorry ;-) But be sure I'll do that tomorrow.

**Comment by csgamedev4linux** [comment]
Thank you very much!

**Comment by demonixis** [comment]
Hi,

I just released a preview version. Please keep in mind that this engine is in ** EARLY  stages ** and it's mainly a research project. However it can be compiled (with works and love) on few platforms such as Linux and Android.
