### ISSUE TITLE
build Editor: dependency missing

### ISSUE THREAD

**Issue by InfiniteProductions** [demonixis/C3DE#3]
In order to build the editor, it also require [WPF toolkit](http://wpftoolkit.codeplex.com/), not listed in the requirements.

**Comment by demonixis** [comment]
The WPF Toolkit is added with nuget.

**Comment by InfiniteProductions** [comment]
Not a very good answer IMHO, nuget sucks and it would be bad to "force" devs to use it even if they don't want to. Anyway, it could be added (automatically) with nuget, it is not by default: download source, try to build => failed.

**Comment by demonixis** [comment]
Visual Studio download it from nuget on my rigs, maybe you try to build it from the command line or from another editor? I can updated the readme with that ;)

**Comment by InfiniteProductions** [comment]
No, just disabled nuget "feature".
IMHO, project should not rely on it only, offering people both the "lazy" way and the "hard" way is better.

**Comment by demonixis** [comment]
Well... that is **your** point. I don't want to debate about features. I'll create a special entry in the readme but I don't want to disable nuget
