### ISSUE TITLE
Editor: missing content: FX/SimpleEffect

### ISSUE THREAD

**Issue by InfiniteProductions** [demonixis/C3DE#4]
Running the editor (from current source tree) lead to an exception in LoadContent method, item FX/SimpleEffect is missing.

**Comment by demonixis** [comment]
The process is not yet complete but you have to build the samples and copy its content folder into the editor's content folder. Morehover, you have to manually generate (with MGCB frontend) the content of the editor and copy it in the bin folder.

**Comment by InfiniteProductions** [comment]
It's a dupe of issue #2 and doing so is not really good, at least you would have to explain your very own build process in a document, good or bad as it is.

Also, for what it's worth, making some "independent" component depends on another component's content is ALWAYS a very bad idea, unfortunately, many XNA based engines and samples does this :(
(Catalinza deferred rendering and Final Engine for example)

Editor, engine core, samples, whatever should be isolated from each other as much as it is possible to do (as your you seems to have such an editor not hardly tied to the engine).

**Comment by demonixis** [comment]
Hi,

In some cases you have not the choice and you can't create independant components.
