### ISSUE TITLE
Lof of file missing in project

### ISSUE THREAD

**Issue by RUSshy** [demonixis/C3DE#7]
Hi,

If you clone project, and load solution Desktop, then load of file missing
So project can't compile

**Comment by demonixis** [comment]
Fixed. 
The desktop solution is not recommanded to use because it misses some features that the MonoGame team haven't implemented.

**Comment by RUSshy** [comment]
I moved to Ultraviolet instead of MonoGame, much better, no content pipeline buggy, runtime assets loading (including glsl shaders), here if you want to check it out https://github.com/tlgkccampbell/ultraviolet it is similar in design

**Comment by demonixis** [comment]
That looks very good! Thanks!
